* The plan....
At some point, contact the publisher to get contact info for the authors' estates.  Then, contact the estates and erm, beg.

- [-] Setup a github repo.
- [-] PAIN
  - [X] Acknowledgements
  - [X] Preface
  - [X] Transliteration and Pronunciation
  - [X] Dates
  - [X] Introduction
  - [X] Chapter 1
  - [X] Chapter 2
  - [-] Chapter 3
    - [X] Text
    - [ ] Inches to cm conversions
  - [-] Chapter 4
    - [X] Text
    - [ ] Weights conversion
  - [-] Chapter 5x
    - [X] Text
    - [ ] Conversions
  - [X] Chapter 6
  - [X] Chapter 7
  - [-] Chapter 8
    - [X] Text
    - [ ] Conversions
  - [X] Chapter 9
  - [X] Chapter 10
  - [X] Chapter 11
  - [X] Chapter 12
  - [ ] Chapter 13
  - [ ] Chapter 14
  - [ ] Chapter 15
  - [ ] Chapter 16
  - [ ] Chapter 17
  - [ ] Chapter 18
  - [ ] Chapter 20
  - [ ] Chapter 21
  - [ ] Chapter 22
  - [ ] Chapter 23
  - [ ] Chapter 24
  - [ ] Chapter 25
  - [ ] Chapter 26
  - [ ] Chapter 27
  - [ ] Chapter 28
  - [X] Appendix 1
  - [ ] Appendix 2
  - [ ] Appendix 3
  - [ ] Appendix 4
  - [ ] Appendix 5
  - [ ] Appendix 6
- [X] Find out what (/sic/) means...
- [ ] The original title can be translated as "Essential Archer for beginners" or "Essential Archery For The Fighting Archer, Or All That the Toiler Desires." Use this!
- [ ] Setup a build script.
- [ ] Lookup [[https://pandoc.org/MANUAL.html#epubs][ePub extras provided by Pandoc]], "index/forward" etc.
- [ ] Styles
  - [ ] Make a reasonable [[https://pandoc.org/MANUAL.html#epub-styling][.css file]].
  - [ ] Page header / footer.
  - [ ] Translator comments in a shaded block.
- [ ] Add the errata.
- [ ] Double-check all Ṭ and ṣ etc.
- [ ] Put the i, ii, iii etc sections back.
- [ ] Find all instances of ~===~ and replace with an explanation of what manuscript it came from.
- [ ] Replace all MSS with "manuscripts".
- [ ] Quick function to replace all:
  - [ ] <char>'<char> with <char>’<char>
  - [ ] <space>'<char> with ‘
  - [ ] <char>'<space> with ’
  - [ ] Add a link to the glossary for all words that appear in it.
- [ ] Then, add notes (groan).
- [ ] Photos for chapter 8, along with a (simplified) hand diagram.
- [ ] Add inches to cm conversions
- [ ] Run a spell check over everything.
- [ ] Ask Bede if he wants to join in, and either update based on more recent research, or add new findings to expand on what's already contained.
- [ ] Publish.
- [ ] Videos?
- [ ] New images?
- [ ] Publish
- [X] No need for an index, when the document can be searched :-)

* Elisp
#+begin_src elisp
(defvar arabic-letters
  '(("a" . "ā")
    ("e" . "ē")
    ("i" . "ī")
    ("o" . "ō")
    ("u" . "ū")
    ("d" . "ḍ")
    ("h" . "ḥ")
    ("H" . "Ḥ")
    ("s" . "ṣ")
    ("T" . "Ṭ")
    ("t" . "ṭ")
    ("z" . "ẓ")))

(defun foggerty-map-character (map)
  (interactive)
  (let* ((char (char-to-string (read-key)))
         (test (assoc char map))
         (replacement (if test (cdr test) char)))
    (insert replacement)
    replacement))

(define-key markdown-mode-map (kbd "<f5>")
                (qif (foggerty-map-character arabic-letters)))

(define-key markdown-mode-map (kbd "'")
            (qif (insert "’")))
(define-key markdown-mode-map (kbd "`")
            (qif (insert "‘")))
(define-key markdown-mode-map (kbd "~")
            (qif (insert "“")))
(define-key markdown-mode-map (kbd "\"")
            (qif (insert "”")))
#+end_src
