* The plan....
At some point, contact the publisher to get contact info for the authors' estates.  Then, contact the estates and erm, beg.

- [X] Setup a github repo.
- [-] PAIN
  - [X] Acknowledgements
  - [X] Preface
  - [X] Transliteration and Pronunciation
  - [X] Dates
  - [X] Introduction
  - [X] Chapter 1
  - [X] Chapter 2
  - [-] Chapter 3
    - [X] Text
    - [ ] Conversions
  - [-] Chapter 4
    - [X] Text
    - [ ] Conversions
  - [-] Chapter 5x
    - [X] Text
    - [ ] Conversions
  - [X] Chapter 6
  - [X] Chapter 7
  - [-] Chapter 8
    - [X] Text
    - [ ] Conversions
  - [X] Chapter 9
  - [X] Chapter 10
  - [X] Chapter 11
  - [X] Chapter 12
  - [X] Chapter 13
  - [X] Chapter 14
  - [-] Chapter 15
    - [X] Text
    - [ ] Conversions
  - [-] Chapter 16
    - [X] Text
    - [ ] Conversions
  - [-] Chapter 17
    - [X] Text
    - [ ] Conversions
  - [X] Chapter 18
  - [-] Chapter 19
    - [X] Text
    - [ ] Conversions
  - [X] Chapter 20
  - [X] Chapter 21
  - [X] Chapter 22
  - [X] Chapter 23
  - [X] Chapter 24
  - [-] Chapter 25
    - [X] Text
    - [ ] Conversions
  - [-] Chapter 26
    - [X] Text
    - [ ] Conversions
  - [X] Chapter 27
  - [X] Chapter 28
  - [X] Appendix 1
  - [-] Appendix 2
    - [X] Text
    - [ ] Links to notes
  - [ ] Appendix 3
  - [-] Appendix 4
    - [X] Text
    - [ ] Finger images
  - [X] Appendix 5
  - [X] Appendix 6
  - [ ] Guide to English terminology
  - [ ] Arabic English glossary
    - [ ] Script to find all terms, and add links from all chapters.
- [ ] Setup a build script.
- [ ] Lookup [[https://pandoc.org/MANUAL.html#epubs][ePub extras provided by Pandoc]], "index/forward" etc.
- [ ] Styles
  - [ ] Make a reasonable [[https://pandoc.org/MANUAL.html#epub-styling][.css file]].
  - [ ] Page header / footer.
- [ ] Then, add notes (groan).
- [ ] Run a spell check over everything, after having deleted custom dict.
- [ ] New images, like, every-fucking-where.  Fuck.  Appendix 5 references plate 18 (reproduction of Taybgha's bow) and if I only include one set of pics, it needs to be this one.
- [ ] Ask Bede if he wants to join in, and either update based on more recent research, or add new findings to expand on what's already contained.
- [ ] The original title can be translated as "Essential Archer for beginners" or "Essential Archery For The Fighting Archer, Or All That the Toiler Desires." Use this!
- [ ] Publish.
- [ ] Videos?
- [X] Add the errata.
- [X] Replace all MSS with "manuscripts".
- [X] Find all instances of ~===~ and replace with an explanation of what manuscript it came from.
- [X] Put the i, ii, iii etc sections back.
- [X] Find out what (/sic/) means...
- [X] Double-check all Ṭ and ṣ etc.
- [X] No need for an index, when the document can be searched :-)

*

* Elisp
#+begin_src elisp
(defvar arabic-letters
  '(("a" . "ā")
    ("e" . "ē")
    ("i" . "ī")
    ("o" . "ō")
    ("u" . "ū")
    ("d" . "ḍ")
    ("h" . "ḥ")
    ("H" . "Ḥ")
    ("s" . "ṣ")
    ("T" . "Ṭ")
    ("t" . "ṭ")
    ("z" . "ẓ")))

(defun foggerty-map-character (map)
  (interactive)
  (let* ((char (char-to-string (read-key)))
         (test (assoc char map))
         (replacement (if test (cdr test) char)))
    (insert replacement)
    replacement))

(define-key markdown-mode-map (kbd "<f5>")
                (qif (foggerty-map-character arabic-letters)))

(define-key markdown-mode-map (kbd "'")
            (qif (insert "’")))
(define-key markdown-mode-map (kbd "`")
            (qif (insert "‘")))
(define-key markdown-mode-map (kbd "~")
            (qif (insert "“")))
(define-key markdown-mode-map (kbd "\"")
            (qif (insert "”")))
#+end_src
