* The plan....
At some point, contact the publisher to get contact info for the authors' estates.  Then, contact the estates and erm, beg.

- [-] Setup a github repo.
- [-] PAIN
  - [X] Acknowledgements
  - [X] Preface
  - [X] Transliteration and Pronunciation
  - [X] Dates
  - [X] Introduction
  - [X] Chapter 1
  - [X] Chapter 2
  - [ ] Chapter 3
  - [ ] Chapter 4
  - [ ] Chapter 5
  - [ ] Chapter 6
  - [ ] Chapter 7
  - [ ] Chapter 8
  - [ ] Chapter 9
  - [ ] Chapter 10
  - [ ] Chapter 11
  - [ ] Chapter 12
  - [ ] Chapter 13
  - [ ] Chapter 14
  - [ ] Chapter 15
  - [ ] Chapter 16
  - [ ] Chapter 17
  - [ ] Chapter 18
  - [ ] Chapter 20
  - [ ] Chapter 21
  - [ ] Chapter 22
  - [ ] Chapter 23
  - [ ] Chapter 24
  - [ ] Chapter 25
  - [ ] Chapter 26
  - [ ] Chapter 27
  - [ ] Chapter 28
  - [X] Appendix 1
  - [ ] Appendix 2
  - [ ] Appendix 3
  - [ ] Appendix 4
  - [ ] Appendix 5
  - [ ] Appendix 6
- [X] Find out what (/sic/) means...
- [ ] The original title can be translated as "Essential Archer for beginners" or "Essential Archery For The Fighting Archer, Or All That the Toiler Desires." Use this!
- [ ] Setup a build script.
- [ ] Lookup [[https://pandoc.org/MANUAL.html#epubs][ePub extras provided by Pandoc]], "index/forward" etc.
- [ ] Styles
  - [ ] Make a reasonable [[https://pandoc.org/MANUAL.html#epub-styling][.css file]].
  - [ ] Page header / footer.
  - [ ] Translator comments in a shaded block.
- [ ] Add the errata.
- [ ] Double-check all Ṭ and ṣ etc.
- [ ] Put the i, ii, iii etc sections back.
- [ ] Find all instances of ~===~ and replace with an explanation of what manuscript it came from.
- [ ] Then, add notes (groan).
- [ ] Photos for chapter 8, along with a (simplified) hand diagram.
- [ ] Add inches to cm conversions
- [ ] Run a spell check over everything.
- [ ] Ask Bede if he wants to join in, and either update based on more recent research, or add new findings to expand on what's already contained.
- [ ] Publish.
- [ ] Videos?
- [ ] New images?
- [ ] Publish
- [X] No need for an index, when the document can be searched :-)

* Elisp
#+begin_src elisp
(defvar arabic-letters
  '(("a" . "ā")
    ("e" . "ē")
    ("i" . "ī")
    ("o" . "ō")
    ("u" . "ū")
    ("d" . "ḍ")
    ("h" . "ḥ")
    ("s" . "ṣ")
    ("T" . "Ṭ")
    ("t" . "ṭ")
    ("z" . "ẓ")
    ("`" . "‛")
    ("'" . "’")))

(defun foggerty-map-character (map)
  (interactive)
  (let* ((char (char-to-string (read-key)))
         (test (assoc char map))
         (replacement (if test (cdr test) char)))
    (insert replacement)
    replacement))

(defun foggerty-map-arabic-letter ()
  "Maps d, h, s, t and z etc. to arabic equivalencies."
  (interactive)
  (foggerty-map-character arabic-letters))

(global-set-key (kbd "<f5>") 'foggerty-map-arabic-letter)
#+end_src
